<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">     
    
    {{ HTML::style('/assets/css/bootstrap.min.css') }}
    <style>
      @media print {
  html, body {
    font-size: 9pt !important;
  }
  tr {page-break-inside: avoid }
    </style>
    <meta name="description" content="Danno's Book is your resource for historical arrest records and background checks in Marin County.">
    <meta name="author" content="Danno's Book">

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
    
    
    <title>
      Print Search Results || Danno's Book
    </title>
    
    
  </head>
  <body>
    <div class="container">
      <div class="row">
	    <div class="col-md-12">
		<h1>Danno's Book Suspect Search ({{ $count }} results)</h1>
		  Generated by {{ Auth::user()->username }} at {{ date(DATE_RFC850)}}
		  <hr />
	    </div>
	    <div class="col-md-12" id="filters">
		  	    <div class="col-md-12">
		  <h3>Suspect Details</h3>
		  <table class="table table-bordered table-striped" id="suspectdata">
			<tbody>
			<tr>
			      <td><strong>Name contains:</strong></td>
			      <td id="name">{{ Input::old('name') }}</td>
			      <td><strong>Gender contains (M/F):</strong></td>
			      <td id="gender">{{ Input::old('gender') }}</td>
			      
			</tr>
			<tr>
			      <td><strong>Hair Color contains:</strong></td>
			      <td id="haircolor">{{ Input::old('haircolor') }}</td>
			      <td><strong>Eye Color contains:</strong></td>
			      <td id="haircolor">{{ Input::old('eyecolor') }}</td>
			</tr>
			<tr>
			      <td><strong>Min Weight (lbs):</strong></td>
			      <td id="minweight">{{ Input::old('minweight', 0) }}</td>
			      <td><strong>Max Weight (lbs):</strong></td>
			      <td id="maxweight">{{ Input::old('maxweight', 2000) }}</td>
			</tr>
			<tr>
			      <td><strong>Min DOB (YYYY-MM-DD):</strong></td>
			      <td id="minage">{{ Input::old('mindob', '1800-01-01') }}</td>
			      <td><strong>Max DOB (YYYY-MM-DD):</strong></td>
			      <td id="maxage">{{ Input::old('maxdob') }}</td>
			</tr>
			<tr>	
			      <td><strong>Home Address contains: </strong></td>
			      <td id="address">{{ Input::old('address') }}</td>
			      <td><strong>Occupation contains:</strong></td>
			      <td id="occupation">{{ Input::old('occupation') }}</td>
			</tr>
			</tbody>
		  </table>
		  <table class="table table-bordered table-striped" id="arrestdata">
			<tbody>
			      <tr>
				    <td><strong>Min Arrest Date (YYYY-MM-DD):</strong></td>
				    <td id="minarrestdate">{{ Input::old('minarrest') }}</td>
				    <td><strong>Max Arrest Date (YYYY-MM-DD):</strong></td>
				    <td id="maxarrestdate">{{ Input::old('maxarrest') }}</td>
			      </tr>
			      <tr>
				    <td><strong>Min Latest Charge Date (YYYY-MM-DD):</strong></td>
				    <td id="minchargedate">{{ Input::old('minlatestcharge') }}</td>
				    <td><strong>Max Latest Charge Date (YYYY-MM-DD):</strong></td>
				    <td id="maxchargedate">{{ Input::old('maxlatestcharge') }}</td>
			      </tr>
			      <tr>
				    <td><strong>Min Booking Date (YYYY-MM-DD):</strong></td>
				    <td id="minbookingdate">{{ Input::old('minbooking', '1800-01-01') }}</td>
				    <td><strong>Max Booking Date (YYYY-MM-DD):</strong></td>
				    <td id="maxbookingdate">{{ Input::old('maxbooking') }}</td>
			      </tr>
			      <tr>
				    <td><strong>Arrest Agency contains:</strong></td>
				    <td id="arrestagency">{{ Input::old('arrestagency') }}</td>
				    <td><strong>Arrest Location contains:</strong></td>
				    <td id="arrestlocation">{{ Input::old('arrestloc') }}</td>
			      </tr>
			</tbody>
		  </table>
		  <table class="table table-bordered table-striped" id="arrestdata">
			<tbody>
			      <tr>
				    <td><strong>Charge ID (e.g. '664 484(A) PC') contains:</strong></td>
				    <td id="maxarrestdate">{{ Input::old('chargeid') }}</td>
				    <td><strong>Type (e.g. 'F', 'M', 'I', etc.) contains:</strong></td>
				    <td id="type">{{ Input::old('type') }}</td>
				    
				    
			      </tr>
			      <tr>
				    <td><strong>Description contains:</strong></td>
				    <td id="minarrestdate">{{ Input::old('description') }}</td>
				    <td><strong>Authority contains:</strong></td>
				    <td id="arrestagency">{{ Input::old('authority') }}</td>
				    
			      </tr>
			      <tr>
				    <td><strong>Min Bail:</strong></td>
				    <td id="maxbookingdate">{{ Input::old('minbail') }}</td>
				    <td><strong>Max Bail:</strong></td>
				    <td id="minbookingdate">{{ Input::old('maxbail') }}</td>
			      </tr>
			</tbody>
		  </table>
		  <hr />	
	    </div>
	    </div>
	    <p style="page-break-after: always; text-align: center;">--- RECORDS BEGIN ---</p>
	    <div class="col-md-12">
		  <h3>Search Results</h3>
		  <table class="table table-bordered table-striped" id="results">
			<thead>
			      <tr> 
				    <td>Name</td>
				    <td>Address</td>
				    <td>Booking Date</td>
				    <td>Latest Charge Date</td>
			      </tr>
			</thead>
			<tbody>
			@foreach($results as $result)
			      <tr> 
				    <td>{{ $result->name }}</td>
				    <td>{{ $result->address }}</td>
				    <td>{{ $result->bookingdate }}</td>
				    <td>{{ $result->latestchargedate }}</td>
			      </tr>
			@endforeach
			</tbody>
		  </table>		
	    </div>
	    </div>
      </div>
      

<hr>
      <center><footer>
        <p>
           Formatting & Display &copy; Danno's Book {{ date('Y') }}
        </p>
      </footer></center>
    </div>
      
      	
    <!-- /container -->
    {{ HTML::script('/assets/js/jquery.min.js') }}
    {{ HTML::script('/assets/js/bootstrap.min.js') }}
    
    <script type="text/javascript">@yield('js', '')</script>
  </body>

</html>