@extends('web.components.boilerplate')

@section('title')
Alleged Offense Counts     
@stop

@section('js')
$(document).ready(function() {
    $('#offenders').dataTable({
      "iDisplayLength": 25,
      "order": [[ 5, "desc" ]]
    });
} );
@stop

@section('content')
@if($datables=true)@endif
<div class="container">
      <div class="row">
        <div class="col-md-12">
	<h1>Alleged Offense Counts</h2>
        </div>
      </div>
      <div class="row">
	    <div class="col-md-12">
		 <h3>Explanation</h3>
		       Offenders are sorted by <strong>Grand Score</strong>, which is a weighted analysis of their crimes (individual scoring per crime is a TODO). The Grand Score is generated by the following formula:
		       <br /><br /><pre>(number of felonies * 8) + (number of misdemeanors * 4) + (number of infractions * 2)</pre><br />
			Also available is Mapped Individual Weighting, which is a way to examine whether their grand score comes primarily from major crimes or lesser ones. The Individual Score is generated by the following forumlae:
			<br /><br /><pre>Grand Score = (number of felonies * 8) + (number of misdemeanors * 4) + (number of infractions * 2)
Total Infractions = number of felonies + number of misdemeanors + number of infractions
Unmapped IW = Grand Score/Total Offenses [this gives us the weighting on a scale of 2 (all infractions) to 8 (all felonies)]
Mapped IW* = (((Unmapped IW-2)/(6)) * (9)) + 1

*General linear transform to move X from an A through B scale to a C through D scale is:
      Y = (X-A)/(B-A) * (D-C) + C
      
Therefore transforming Unmapped IW from 2 through 8 to 0 through 10 is:
      Mapped IW = (((Unmapped IW-2)/(8-2)) * (10-0)) + 0
      Mapped IW = ((Unmapped IW-2)/(6)) * (10)
</pre>
			      <hr />
		  <h3>Display</h3>
		       <table class="table-bordered table-striped" id="offenders">
			     <thead>
				    <tr> 
					  <td>Name</td>
					  <td>Felonies</td>
					  <td>Misdemeanor</td>
					  <td>Infractions</td>
					  <td>Total Offenses</td>
					  <td>Grand Score</td>
					  <td>MIW (0-10)</td>
				    </tr>
			     </thead>
			     <tbody>
			     @foreach($offenders as $offender)
				   <?php
				    $totaloffenses = $offender->felonies + $offender->misdemeanors + $offender->infractions;
				    $grandscore = ($offender->felonies*8) + ($offender->misdemeanors*4) + ($offender->infractions*2);
				    if(!$totaloffenses){
					  $totaloffenses = 1;
				    }
				    
				    $unmappediw = ($grandscore/$totaloffenses);				    
				    $mappediw = (($unmappediw-2)/(6)) * 10
				    ?>
				    <tr> 
					  <td><a href="{{ URL::action('SuspectController@getView', array('id'=>$offender->bookee_id)) }}">{{ Privacylib::privName($offender->name) }}</a></td>
					  <td>{{ $offender->felonies }}</td>
					  <td>{{ $offender->misdemeanors }}</td>
					  <td>{{ $offender->infractions }}</td>
					  <td>{{ $totaloffenses }}</td>
					  <td>{{ $grandscore }}</td>
					  <td>{{ round($mappediw, 2) }}</td>
				    </tr>
			     @endforeach
			     </tbody>
			   </table>
		       
	    </div>
      </div>
@stop